### ISSUE TITLE
Failing behat test - export.feature

### ISSUE THREAD

**Issue by AdilIqbal95** [dualcube/Drag-and-Drop-Matching#21]
Hi, the test stated above is failing.

**Environment details:**
MySQL 5.7
PHP 7.4
Moodle latest MOODLE_400_STABLE

**Error details:**
**Scenario: Export a Drag and drop matching question**
And I set the field "id_format_xml" to "1": Field matching locator "id_format_xml" not found. (Behat\Mink\Exception\ElementNotFoundException)

**Comment by moumitahalder** [comment]
Hi @AdilIqbal95, please check with the latest version of Drag and Drop and check.
