### ISSUE TITLE
No define call for core_form/changechecker

### ISSUE THREAD

**Issue by pliniopecanha** [dualcube/Drag-and-Drop-Matching#26]
After the upgrade, I now have this problem.

```
Uncaught Error: No define call for **core_form/changechecker**
http://requirejs.org/docs/errors.html#nodefine
    makeError https://mymoodle.com/lib/javascript.php/1674158670/lib/requirejs/require.min.js:5
    completeLoad https://mymoodle.com/lib/javascript.php/1674158670/lib/requirejs/require.min.js:5
    onScriptLoad https://mymoodle.com/lib/javascript.php/1674158670/lib/requirejs/require.min.js:5
require.min.js:5:1067
    makeError https://mymoodle.com/lib/javascript.php/1674158670/lib/requirejs/require.min.js:5
    completeLoad https://mymoodle.com/lib/javascript.php/1674158670/lib/requirejs/require.min.js:5
    onScriptLoad https://mymoodle.com/lib/javascript.php/1674158670/lib/requirejs/require.min.js:5
```

This keeps preventing the question from working well, it simply loses the drag and drop function.

The Moodle with the problem is version 3.10.
On moodle 4.0 it works fine.

Could you please check?

**Comment by V3ndetta** [comment]
Same Issue for me. 
Uncaught Error: No define call for core_form/changechecker
No Drag-Drop functionality anymore on Moodle 3.11.12

**Comment by glennarcher-nz** [comment]
We have the same issue in Moodle 3.9 our upgrade for 4.0 is until April, can you give the previous version of this plugin so we can use it still

**Comment by kundandualcube** [comment]
it's solved and added in the latest version

**Comment by glennarcher-nz** [comment]
Thank you for this
