### ISSUE TITLE
Drag-and-Drop matching with several identical answers doesn't work

### ISSUE THREAD

**Issue by twobaker** [dualcube/Drag-and-Drop-Matching#27]
See also: [CONTRIB-9212](https://tracker.moodle.org/browse/CONTRIB-9212) 

If I have a ddmatch question with several identical answers, this is no longer possible in version 2.1, because answers can only be used once. From my point of view, this is a mistake.

**Reproduce:**
1. Create a question with the question type drag-and-drop matching.
2. Choose the same answer for several questions
3. Test the question in the preview or in a quiz and each answer is only available for selection once and not several times.

**Same question in a short GIF to show the behaviour:**
* Working in Moodle 3.9.17 (ddmatch 2.0): https://imgur.com/jbp5O3l
* Not working in Moodle 4.1.1 (ddmatch 2.1): https://imgur.com/IY8J7Go

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
