### ISSUE TITLE
CSS Problem: breaks all the site

### ISSUE THREAD

**Issue by ppv1979** [dualcube/Drag-and-Drop-Matching#3]
After 5643ddb by @trideepdm CSS styles in several other places at website were broken (for example in other tables). 
I think it was because of not using _.ddmatch_ class before such blocks as
```
tr {
     word-break: break-all;
 }
```
```
p, .text {
     font-size: 15px !Important;
     word-break: break-word;
     line-height: 20px;
     color: #333;
 }
```

Can you check the styles.css carefully to fix all such situations?

**Comment by dinism** [comment]
I have the same problem?
![imagem](https://user-images.githubusercontent.com/14828021/83358436-6fc17900-a36b-11ea-97b2-18661ef610cf.png)

**Comment by jlhollowell** [comment]
Same problem here as well. Fixed using the following:

.ddmatch tr {
word-break: break-all;
}

That seems to be limiting break-all to the drag and drop question type.

**Comment by schiem** [comment]
#4

**Comment by trideepdm** [comment]
Dear,
Please update your plugin. This issue has been fixed on our last update.
Thank you.
