### ISSUE TITLE
Moodle 3.9 - PHPUnit -  Undefined property: stdClass::$idnumber

### ISSUE THREAD

**Issue by aspark21** [dualcube/Drag-and-Drop-Matching#5]
15) qtype_ddmatch_test::test_get_random_guess_score
Undefined property: stdClass::$idnumber

/path/to/moodle/question/type/questiontypebase.php:911
/path/to/moodle/question/type/ddmatch/questiontype.php:119
/path/to/moodle/question/type/questiontypebase.php:872
/path/to/moodle/question/type/ddmatch/questiontype.php:159
/path/to/moodle/question/type/ddmatch/tests/questiontype_test.php:119
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_ddmatch_test" question/type/ddmatch/tests/questiontype_test.php

**Comment by aspark21** [comment]
Tested on Moodle 3.9.1 and ddmatch 2020071100 - still an issue.

**Comment by aspark21** [comment]
Also picked up by:
qtype_ddmatch_test::test_get_possible_responses
    Undefined property: stdClass::$idnumber
  
    /var/www/html/question/type/questiontypebase.php:911
    /var/www/html/question/type/ddmatch/questiontype.php:119
    /var/www/html/question/type/questiontypebase.php:872
    /var/www/html/question/type/ddmatch/questiontype.php:166
    /var/www/html/question/type/ddmatch/tests/questiontype_test.php:141
    /var/www/html/lib/phpunit/classes/advanced_testcase.php:80
  
    To re-run:
     vendor/bin/phpunit "qtype_ddmatch_test" question/type/ddmatch/tests/questiontype_test.php

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
