### ISSUE TITLE
Moodle 3.9 - PHPunit - count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by aspark21** [dualcube/Drag-and-Drop-Matching#6]
qtype_ddmatch_walkthrough_test::test_ddmatch_clear_wrong
count(): Parameter must be an array or an object that implements Countable

/path/to/moodle/lib/phpunit/classes/base_testcase.php:58
/path/to/moodle/question/engine/tests/helpers.php:496
/path/to/moodle/question/engine/tests/helpers.php:1004
/path/to/moodle/question/type/ddmatch/tests/walkthrough_test.php:427
/path/to/moodle/lib/phpunit/classes/advanced_testcase.php:80

**Comment by trideepdm** [comment]
Dear,
This plugin is working fine on our testing moodle instance and also not getting this error. Can you please specify where or how you encounter this error?
Thank you.

**Comment by aspark21** [comment]
Hi trideepdm 

This comes up when running the PHPUnit tests (https://docs.moodle.org/dev/PHPUnit)

Thanks
Alistair

**Comment by aspark21** [comment]
Re-tested on Moodle 3.9.1 and ddmatch 2020071100. Confirm fixed.
