### ISSUE TITLE
Implement Privacy API

### ISSUE THREAD

**Issue by aspark21** [dualcube/Drag-and-Drop-Matching#7]
provider_testcase::test_all_providers_compliant with data set "qtype_ddmatch" ('qtype_ddmatch', 'qtype_ddmatch\privacy\provider')
    Failed asserting that false is true.
  
    /var/www/html/privacy/tests/provider_test.php:178
    /var/www/html/lib/phpunit/classes/advanced_testcase.php:80
  
    To re-run:
     vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

https://docs.moodle.org/dev/Privacy_API#Implementing_a_provider

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
