### ISSUE TITLE
Behat undefined Question Bank step

### ISSUE THREAD

**Issue by aspark21** [dualcube/Drag-and-Drop-Matching#9]
Moodle 3.9.2
ddmatch - master

 /var/www/html/question/type/ddmatch/tests/behat/add.feature:7
And I am on "Course 1" course homepage                            # behat_hooks::i_look_for_exceptions()
    And I navigate to "Question bank" node in "Course administration"
    â”‚
    â•³  Coding error detected, it must be fixed by a programmer: Step 'I navigate to "Question bank" node in "Course administration"'' is undefined. (coding_exception)
    â”‚
    â””â”€ @AfterStep # behat_hooks::after_step_javascript()

https://github.com/dualcube/Drag-and-Drop-Matching/blob/master/tests/behat/add.feature#L19

**Comment by aspark21** [comment]
Also:
https://github.com/dualcube/Drag-and-Drop-Matching/blob/master/tests/behat/backup_and_restore.feature#L34

Correct implementation: https://github.com/moodle/moodle/blob/master/question/type/ddwtos/tests/behat/add.feature#L19
Change due to https://tracker.moodle.org/browse/MDL-57281

**Comment by aspark21** [comment]
Coding error detected, it must be fixed by a programmer: Step 'I navigate to "Import" node in "Course administration > Question bank"'' is undefined. (coding_exception)

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
